# Generated by Django 4.1.5 on 2023-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Атауы')),
                ('date', models.CharField(max_length=250, verbose_name='Тур уақыты')),
                ('equipment', models.CharField(max_length=20, verbose_name='Номер типі')),
                ('price', models.IntegerField(verbose_name='Тур бағасы')),
                ('img', models.IntegerField(verbose_name='Фото енгіз')),
                ('category_id', models.ForeignKey()),
            ],
        ),
    ]
