# Generated by Django 4.1.5 on 2023-02-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tours',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Турлар'},
        ),
        migrations.AlterField(
            model_name='tours',
            name='img',
            field=models.CharField(max_length=450, verbose_name='Фото енгізіңіз'),
        ),
    ]
